// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProgramacionAvanzada.Books.Model;

#nullable disable

namespace MyNewMvcApp.Migrations
{
    [DbContext(typeof(BooksDbContext))]
    [Migration("20251122175618_AddLostDateToBookCopies")]
    partial class AddLostDateToBookCopies
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("utf8mb4_0900_ai_ci")
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.HasCharSet(modelBuilder, "utf8mb4");
            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Author", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Edition")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EnglishTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("OriginalTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookAuthor", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "AuthorId")
                        .HasName("PRIMARY");

                    b.HasIndex("AuthorId");

                    b.ToTable("bookauthors", (string)null);
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookCopy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("DateCreated")
                        .HasColumnType("date");

                    b.Property<string>("ISBN")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<bool?>("IsLost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValueSql("'0'");

                    b.Property<string>("Language")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LostDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Provider")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Serial")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookId" }, "BookId");

                    b.ToTable("BookCopies");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookTheme", b =>
                {
                    b.Property<int>("BookId")
                        .HasColumnType("int");

                    b.Property<int>("ThemeId")
                        .HasColumnType("int");

                    b.HasKey("BookId", "ThemeId")
                        .HasName("PRIMARY");

                    b.HasIndex("ThemeId");

                    b.ToTable("bookthemes", (string)null);
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Borrow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookCopyId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("FinalDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("InitialDate")
                        .HasColumnType("date");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("RealDevolutionDate")
                        .HasColumnType("date");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.HasIndex(new[] { "BookCopyId" }, "BookCopyId");

                    b.HasIndex(new[] { "PersonId" }, "PersonId");

                    b.ToTable("Borrows");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Sex")
                        .HasMaxLength(1)
                        .HasColumnType("char(1)")
                        .IsFixedLength();

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Persons");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Theme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Subject")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ThemeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id")
                        .HasName("PRIMARY");

                    b.ToTable("Themes");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookAuthor", b =>
                {
                    b.HasOne("ProgramacionAvanzada.Books.Model.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .IsRequired()
                        .HasConstraintName("bookauthors_ibfk_2");

                    b.HasOne("ProgramacionAvanzada.Books.Model.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("bookauthors_ibfk_1");

                    b.Navigation("Author");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookCopy", b =>
                {
                    b.HasOne("ProgramacionAvanzada.Books.Model.Book", "Book")
                        .WithMany("BookCopies")
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("bookcopies_ibfk_1");

                    b.Navigation("Book");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookTheme", b =>
                {
                    b.HasOne("ProgramacionAvanzada.Books.Model.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .IsRequired()
                        .HasConstraintName("bookthemes_ibfk_1");

                    b.HasOne("ProgramacionAvanzada.Books.Model.Theme", "Theme")
                        .WithMany()
                        .HasForeignKey("ThemeId")
                        .IsRequired()
                        .HasConstraintName("bookthemes_ibfk_2");

                    b.Navigation("Book");

                    b.Navigation("Theme");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Borrow", b =>
                {
                    b.HasOne("ProgramacionAvanzada.Books.Model.BookCopy", "BookCopy")
                        .WithMany("Borrows")
                        .HasForeignKey("BookCopyId")
                        .IsRequired()
                        .HasConstraintName("borrows_ibfk_1");

                    b.HasOne("ProgramacionAvanzada.Books.Model.Person", "Person")
                        .WithMany("Borrows")
                        .HasForeignKey("PersonId")
                        .IsRequired()
                        .HasConstraintName("borrows_ibfk_2");

                    b.Navigation("BookCopy");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Book", b =>
                {
                    b.Navigation("BookCopies");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.BookCopy", b =>
                {
                    b.Navigation("Borrows");
                });

            modelBuilder.Entity("ProgramacionAvanzada.Books.Model.Person", b =>
                {
                    b.Navigation("Borrows");
                });
#pragma warning restore 612, 618
        }
    }
}
